interact.js

Elements that are in Shadow DOMs can be interacted with.
```javascript
interact('custom-element')
.draggable(/* ... */)
.on('tap', function (event) { /* ... */ });
```
There are a few issues:
1. ~~Because of what I think might be a bug in Blink,~~ `Element.matches` always fails with deep/shadow-piercing selectors. For example, try running this on https://polymer-project.org:
`var selector = 'paper-button::shadow *';`
`document.querySelector(selector).matches(selector); // false`
So such selectors won't work with interact.js.
2. `:host`, `::shadow`, `::content` selectors cause errors if used with the Shadow DOM polyfill
3. Dropzones haven't been tested

Add support for Shadow DOM (native or using polyfill)

---

interact.js

```javascript
interact(target)
.dropzone(true)
.dropChecker(function (pointer,            // pointer/event that ends drag
dropped,            // value from default drop check
dropzone,           // dropzone Interactable
dropElement,        // dropzone Element
draggable,          // draggable Interactable
draggableElement) { // Element being dragged
// use the default value with another custom condition
return dropped && someCondition;
});
```

Pass the default dropCheck result to dropCheckers

---

interact.js

I did some debugging today to find out that my event handlers are still holding references to my DOM elements after calling 'unset'.  These changes seem to correct the issue.  Please let me know what you think!

Bugfix for calling unset method on an Interactable

---

interact.js

I think this was forgotten with cc14819, I just realised tap.dt is NaN on touchscreen devices, now it works fine.

Fix pointer dt on touchscreen devices

---

interact.js

Suggestion to add the ability to optionally confine autoScroll in the horizontal or vertical direction.

Optionally limit horizontal, vertical autoScroll

---

src/Interactable.js
src/Interaction.js
src/interact.js
src/legacyBrowsers.js
src/scope.js

Event listeners are no longer automatically added to the parent window if the script is loaded in an iframe with a parent of the same origin to avoid [potential memory leaks](#311). `preventDefault` is no longer called on `down` events with the `'auto'` setting. This allows mouse move and up events to be fired on the iframe even when the mouse is dragged outside the iframe borders and over the parent document.
`interact.addDocument(document)` and `interact.removeDocument(document)` methods have been added to allow listening to different documents, e.g:
```javascript
// try to listen to events on the parent document if this is an iframe
try {
if (window.frameElement) {
const parentDoc = window.frameElement.ownerDocument;
const parentWindow = parentDoc.defaultView; …
```

Improve iframe support

---

README.md

Sub-directory should be `vendor/assets/javascripts/interact` not `app/vendor/assets/javascripts/interact`. See [Asset Organization for Rails 4](http://guides.rubyonrails.org/v4.0.8/asset_pipeline.html#asset-organization) for proper asset directories.

Fix wrong directory in Rails Installation section

---

src/actions/drop.js

I think there is one line of if statement is redundant in the drop file of drag move event.

Remove redundant dragmove fired

---

src/modifiers/restrict.js
src/modifiers/restrictEdges.js
src/modifiers/restrictSize.js
tests/actions/base.js
tests/actions/drag.js
tests/index.js
tests/modifiers/restrictSize.js

* Don't require page arguments if they won't be used.
* Update restrictSize to use inner/outer syntax.
* Fix a syntax error in restrictEdges (`page` should be an argument to `getRestrictionRect`).
Fixes #507 
Edit 2: Behavior fixed, tests updated with correct expectations.
Edit 3: Just found what seems to be another issue where the `restrictSize` option value seems to be shared between multiple interactables. Mentioning in case it makes sense to address as part of this PR.

modifiers/restrict: fix restrictSize, restrictEdges

---

index.d.ts
package.json

This fixes a series of issues with the typescript typings:
1. The previous code was set in a way that the typings were not automatically discoverable by the TypeScript compiler. There are multiple ways to solve the issue. The simplest one given the presence of `index.js` is just to rename the typings `index.d.ts`, which is what I did.
2. The `.d.ts` file contained a hardcoded module name. There's no reason for this. I've modified the file to remove the hardcoded name and at the same time took care to edit it so that it works both when interact.js is loaded as a module and when it is assumed to have been preloaded into the global space.
3. I fixed the way the ``restrict`` option was defined.

Fix the TypeScript definitions

---

src/utils/browser.js

This fixes issue raised by Closure Compiler:
ERROR - Illegal variable reference before declaration: browser

Fix Illegal variable reference before declaration: browser

---

src/autoStart/base.js
src/index.js
src/reflow.js
tests/index.js
tests/reflow.js

```js
const interactable = interact(target);
const drag = { name: drag, axis: 'x' };
const resize = { name: resize, edges: { left: true, bottom: true };
interactable.reflow(drag);
interactable.reflow(resize);
```
Close #413 #246 #212

`interactable.reflow(action)` to re-run modifiers, drop, etc

---

src/actions/drop/DropEvent.js
src/actions/drop/index.js
tests/actions/drop/DropEvent.js

```html
<div class="container" data-color="red"></div>
<div class="container" data-color="green"></div>
<div class="draggable" data-color="red">Item 1</div>
<div class="draggable" data-color="blue">Item 2</div>
<div class="draggable" data-color="green">Item 3</div>
<script>
interact('.container')
.dropzone({
accept: '.draggable',
})
.on('dragenter', event => {
const dropzoneElement = event.target;
const draggableElement = event.relatedTarget;
if (draggableElement.dataset.color !== dropzoneElement.dataset.color) {
event.reject();
}
})
.on('drop', event => {
console.log('dropped');
});
</script>
```
Clse #552

DropEvent.reject()

---

README.md
packages/_dev/test/helpers.js
packages/inertia/index.js
packages/interact/index.js
packages/modifiers/README.md
packages/modifiers/base.js
packages/modifiers/index.js
packages/modifiers/restrict.js
packages/modifiers/restrictEdges.js
packages/modifiers/restrictSize.js
packages/modifiers/snap.js
packages/modifiers/snapSize.js
packages/modifiers/tests/base.js
packages/modifiers/tests/restrictEdges.js
packages/modifiers/tests/restrictSize.js
packages/modifiers/tests/snap.js
packages/modifiers/tests/snapEdges.js
packages/modifiers/tests/snapSize.js

```js
const restrictToParent = interact.modifiers.restrict({
restriction: 'parent',
elementRect: { left: 0, right: 0, top: 1, bottom: 1 },
})
const snap100x100 = interact.modifiers.snap({
targets: [interact.snappers.grid({ x: 100, y: 100 })],
}),
interact(target).draggable({
modifiers: [restrictToParent, snap100x100],
})
```
Close #208

Per-action modifiers array

---

packages/actions/drop/index.ts
packages/auto-scroll/index.ts
packages/core/Interactable.spec.ts
packages/core/InteractableSet.ts
packages/core/Interaction.spec.ts
packages/core/Interaction.ts
packages/core/scope.ts
packages/interact/interact.spec.ts
scripts/test.sh

A proposed solution for the issue #713 
This solution adds a more complete cleaning routine to the `unset` method in order to remove all detached elements.
Also contains a little compatibility fix for the `test.sh` script that was not working on my MacOs (Mojave 10.14.4).
Cheers !

Fix: Memory leak - Detached HTML elements

---

src/actions/gesture.js

Gesture events shouldn't be fired twice once in gesture.js and once in base.js
Should fix bug  #695 for the 1.3 branch

remove duplicate gesture event

---

docs/restriction.md
packages/modifiers/index.ts
packages/modifiers/restrict/edges.ts
packages/modifiers/restrict/pointer.spec.ts
packages/modifiers/restrict/pointer.ts
packages/modifiers/restrict/rect.ts
packages/types/types.d.ts
packages/utils/rect.ts

Also add `interact.modifiers.restrictRect` with pre-set `elementRect` option.
```js
interact(target).draggable({
modifiers: [interact.modifiers.restrictRect({
restriction: 'parent',
// elementRect defaults to `{ top: 0, left: 0, bottom: 1, right: 1 }`
}]
})
```
Close #159

feat(modifiers/restrict): restrict intuitively to smaller restrictions

---

docs/draggable.md
docs/resizable.md
packages/auto-start/autoStart.spec.ts
packages/auto-start/base.ts
packages/types/types.d.ts
packages/utils/pointerUtils.ts

```js
interact(target).draggable({
cursorChecker: (action, interactable, element) => {
switch (action.axis) {
case 'x': return 'ew-resize'
case 'y': return 'ns-resize'
case 'xy': return 'grab'
}
}
})
```
Close #698

feat(auto-start): custom cursors with cursorChecker function

---

packages/@interactjs/auto-scroll/plugin.ts

autoScroll can already use css selectors to find appropriate container element, but TypeScript doesn't know about it and throws a compilation error. This fixes that.

fix(auto-scroll): add 'string' type to union of container types for AutoScrollOption

---

packages/@interactjs/actions/package.json
packages/@interactjs/auto-scroll/package.json
packages/@interactjs/auto-start/package.json
packages/@interactjs/core/package.json
packages/@interactjs/dev-tools/package.json
packages/@interactjs/inertia/package.json
packages/@interactjs/interact/package.json
packages/@interactjs/modifiers/package.json
packages/@interactjs/offset/package.json
packages/@interactjs/pointer-events/package.json
packages/@interactjs/reflow/package.json
packages/@interactjs/snappers/package.json
packages/@interactjs/types/package.json
packages/@interactjs/utils/package.json

Hi there!
This change adds the repository property to your package.json file(s). Having this available provides a number of benefits to security tooling. For example, it allows for greater trust by checking for signed commits, contributors to a release and validating history with the project. It also allows for comparison between the source code and the published artifact in order to detect attacks on authors during the publication process.
We validate that we're making a PR against the correct repository by comparing the metadata for the published artifact on [npmjs.com](www.npmjs.com) against the metadata in the package.json file in the repository.
This change is provided by a team at Microsoft -- we're happy to answer any questions you may have. (Members of this team include …

Update package.json to include the repository

---

packages/@interactjs/modifiers/aspectRatio.ts

Sorry, PR #945 closed due to bad push force ^^
Here is the new PR with the updated "main" branch.
The last message:
Fixed the bug when creating a resizable element with a "modifier": "aspectRatio". The top right and bottom left angle works in reverse.
Here is an example: https://codepen.io/tups/pen/RwLgmLO
Fixed issue : https://github.com/taye/interact.js/issues/944

Bug Resizable with modifier aspectRatio
